# Memoria y rendimiento de Gradle
org.gradle.jvmargs=-Xmx2G -XX:+UseG1GC
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=false
org.gradle.vfs.watch=true

# Opcional: acelera builds repetidos. ModDevGradle suele llevarse bien con ella,
# pero si algo falla raro, déjala comentada.
# org.gradle.configuration-cache=true

# NeoForge
neoforge_version=26.2.0.8-beta
moddev_version=2.0.141

# Mod
mod_id=orthocamera
mod_version=0.1.11+26.2-neoforge
maven_group=com.dimaskama
archives_base_name=OrthoCamera